/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.EvidencijaVoznje;
import domen.Sluzbenik;
import domen.Vozilo;
import forme.model.EvidencijaTableModel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;
import util.Util;

/**
 *
 * @author BOJAN
 */
public class FrmDetaljiVozila extends javax.swing.JFrame {

    private final DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
    private static Sluzbenik sluzbenik;
    private int idVozila;
    private Date datumPocetkaSluzbe;
    private Double ukupnaKilometrazaProvera;

    /**
     * Creates new form FrmDetaljiVozila
     */
    public FrmDetaljiVozila(Sluzbenik sluzbenik) {
        initComponents();
        this.sluzbenik=sluzbenik;
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtVoziloID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtDatumPocetkaSluzbe = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtVIN = new javax.swing.JTextField();
        jtxtRegistarskaOznaka = new javax.swing.JTextField();
        jtxtMarka = new javax.swing.JTextField();
        jtxtModel = new javax.swing.JTextField();
        jtxtUkupnaKilometraza = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEvidencijaVozilo = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("ID vozila:");

        jLabel2.setText("Datum po\u010Detka slu\u017Ebe:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o vozilu"));

        jLabel3.setText("VIN:");

        jLabel4.setText("Registarska oznaka:");

        jLabel5.setText("Marka");

        jLabel6.setText("Model:");

        jLabel7.setText("Ukupna kilometra\u017Ea:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(jtxtRegistarskaOznaka, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(84, 84, 84)
                        .addComponent(jtxtVIN))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(jtxtUkupnaKilometraza, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)
                        .addComponent(jtxtMarka, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(73, 73, 73)
                        .addComponent(jtxtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtRegistarskaOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtUkupnaKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnIzmeni))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtDatumPocetkaSluzbe, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jtxtVoziloID))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtxtVoziloID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxtDatumPocetkaSluzbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIzmeni)
                            .addGap(11, 11, 11)))
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Podaci o vozilu", jPanel1);

        jtblEvidencijaVozilo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblEvidencijaVozilo);

        jLabel8.setText("Podaci o svim vo\u017Enjama za vozilo:");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel10)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Evidentirane vo\u017Enje", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {

            if (jtxtVIN.getText().trim().equals("") || jtxtRegistarskaOznaka.getText().trim().equals("") || jtxtMarka.getText().trim().equals("") || jtxtModel.getText().trim().equals("") ||
                jtxtUkupnaKilometraza.getText().trim().equals("")){

                JOptionPane.showMessageDialog(this, "Polja moraju biti popunjena", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Double kilometrazaUkupna;
            try {
                kilometrazaUkupna=Double.parseDouble(jtxtUkupnaKilometraza.getText().trim());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Morate uneti broj u polje Ukupna Kilometra\u017Ea!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (kilometrazaUkupna<ukupnaKilometrazaProvera) {
                JOptionPane.showMessageDialog(this, "Ne mo\u017Eete unositi manju kilometra\u017Eu!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (jtxtVIN.getText().trim().length()!=17) {
                JOptionPane.showMessageDialog(this, "VIN mora sadr\u017Eati 17 znakova!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int id = Integer.parseInt(jtxtVoziloID.getText().trim());

            String vin = jtxtVIN.getText().trim();
            String registarskaOznaka = jtxtRegistarskaOznaka.getText().trim().toUpperCase();
            Date datumPS = df.parse(jtxtDatumPocetkaSluzbe.getText().trim());
            String marka = jtxtMarka.getText().trim();
            String model = jtxtModel.getText().trim();
            Double ukupnaKilometraza = Double.parseDouble(jtxtUkupnaKilometraza.getText().trim());

            Vozilo v = new Vozilo(id, datumPS, vin,registarskaOznaka, marka, model, ukupnaKilometraza);

            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.ZAPAMTI_VOZILO);
            toZahtev.setParametar(v);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();

            boolean sacuvano = (boolean) toOdgovor.getRezultat();

            if (sacuvano) {

                JOptionPane.showMessageDialog(this, "Sistem je zapamtio podatke o vozilu.");
                // isprazniTxtPolja();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da zapamti podatke o vozilu!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetaljiVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetaljiVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetaljiVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetaljiVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDetaljiVozila(sluzbenik).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtblEvidencijaVozilo;
    private javax.swing.JTextField jtxtDatumPocetkaSluzbe;
    private javax.swing.JTextField jtxtMarka;
    private javax.swing.JTextField jtxtModel;
    private javax.swing.JTextField jtxtRegistarskaOznaka;
    private javax.swing.JTextField jtxtUkupnaKilometraza;
    private javax.swing.JTextField jtxtVIN;
    private javax.swing.JTextField jtxtVoziloID;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        try {
            
            Vozilo vozilo = (Vozilo) Util.getInstance().get("izabrano_vozilo");
            if (vozilo != null) {
                this.setTitle("Rad sa vozilom: "+vozilo.toString());
                jtxtVoziloID.setText(String.valueOf(vozilo.getVoziloID()));
                jtxtVoziloID.setEditable(false);
                jtxtDatumPocetkaSluzbe.setEditable(false);
                jtxtDatumPocetkaSluzbe.setText(df.format(vozilo.getDatumPocetkaSluzbe()));
                jtxtMarka.setText(vozilo.getMarka());
                jtxtModel.setText(vozilo.getModel());
                jtxtRegistarskaOznaka.setText(vozilo.getRegistarskaOznaka());
                jtxtVIN.setText(vozilo.getVin());
                jtxtUkupnaKilometraza.setText(String.valueOf(vozilo.getUkupnaKilometraza()));
                //jtxtUkupnaKilometraza.setEditable(false);
                
                idVozila= vozilo.getVoziloID();
                datumPocetkaSluzbe = vozilo.getDatumPocetkaSluzbe();
                
                jLabel9.setText(vozilo.toString());
                
                ukupnaKilometrazaProvera = vozilo.getUkupnaKilometraza();
                
                Util.getInstance().remove("izabrano_vozilo");
                               
                TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
                toZahtev.setOperacija(Konstante.UCITAJ_VOZILO);
                toZahtev.setParametar(vozilo);
                Komunikacija.getInstance().posaljiZahtev(toZahtev);
                TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();

                List<EvidencijaVoznje> listaPronadjenihEvidencija = (List<EvidencijaVoznje>) toOdgovor.getRezultat();

                if (listaPronadjenihEvidencija.isEmpty()) {
                    EvidencijaTableModel modelnadjeni = new EvidencijaTableModel(null);
                    jtblEvidencijaVozilo.setModel(modelnadjeni);
                    System.out.println("Sistem ne mo\u017Ee da na\u0111e evidencije za ovo vozilo.");
                    //JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da na\u0111e evidencije za ovo vozilo!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                    jLabel10.setText("Ne postoje evidentirane vo\u017Enje za ovo vozilo.");
                }

                else {

                    EvidencijaTableModel modelnadjeni = new EvidencijaTableModel(listaPronadjenihEvidencija);
                    jtblEvidencijaVozilo.setModel(modelnadjeni);
                    System.out.println("Sistem je na\u0161ao evidencije.");
                    jLabel10.setText("");

                }
                            
                JOptionPane.showMessageDialog(this,"Sistem je na\u0161ao podatke o izabranom vozilu.");
            } else {
               JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da na\u0111e podatke o izabranom vozilu!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmDetaljiVozila.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

}
