/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Sluzbenik;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import komunikacija.Komunikacija;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author BOJAN
 */
public class FrmGlavna extends javax.swing.JFrame {
    
    private static Sluzbenik sluzbenik;

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna(Sluzbenik s) {
        this.sluzbenik = s;
        initComponents();
        this.setTitle("Taksi slu\u017Eba");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        jmiUnosTaksista = new javax.swing.JMenuItem();
        jmiUnosVozila = new javax.swing.JMenuItem();
        jmiUnosEvidencije = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiPretragaTaksista = new javax.swing.JMenuItem();
        jmiPretragaVozila = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        JMenu1.setText("Unos");

        jmiUnosTaksista.setText("Taksista");
        jmiUnosTaksista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosTaksistaActionPerformed(evt);
            }
        });
        JMenu1.add(jmiUnosTaksista);

        jmiUnosVozila.setText("Vozila");
        jmiUnosVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosVozilaActionPerformed(evt);
            }
        });
        JMenu1.add(jmiUnosVozila);

        jmiUnosEvidencije.setText("Evidencije vo\u017Enje");
        jmiUnosEvidencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosEvidencijeActionPerformed(evt);
            }
        });
        JMenu1.add(jmiUnosEvidencije);

        jMenuBar1.add(JMenu1);

        jMenu2.setText("Pretraga");

        jmiPretragaTaksista.setText("Taksista");
        jmiPretragaTaksista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaTaksistaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretragaTaksista);

        jmiPretragaVozila.setText("Vozila");
        jmiPretragaVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaVozilaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPretragaVozila);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosVozilaActionPerformed
        FrmUnosVozila frmUnosV = new FrmUnosVozila();
        frmUnosV.setVisible(true);
        frmUnosV.setTitle("Unos vozila");
        frmUnosV.setDefaultCloseOperation(FrmUnosVozila.DISPOSE_ON_CLOSE);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - frmUnosV.getWidth()) / 2;
        final int y = (screenSize.height - frmUnosV.getHeight()) / 2;
        frmUnosV.setLocation(x, y);
    }//GEN-LAST:event_jmiUnosVozilaActionPerformed

    private void jmiUnosTaksistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosTaksistaActionPerformed
        FrmUnosTaksista frmUnosT = new FrmUnosTaksista();
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - frmUnosT.getWidth()) / 2;
        final int y = (screenSize.height - frmUnosT.getHeight()) / 2;
        frmUnosT.setLocation(x, y);
        frmUnosT.setVisible(true);
        frmUnosT.setTitle("Unos taksista");
        frmUnosT.setDefaultCloseOperation(FrmUnosTaksista.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jmiUnosTaksistaActionPerformed

    private void jmiUnosEvidencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosEvidencijeActionPerformed
        FrmUnosEvidencija evidencijafrm = new FrmUnosEvidencija(sluzbenik);
        JDialog dialog = new JDialog(this, "Unos evidencije", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(evidencijafrm, BorderLayout.CENTER);
        dialog.pack();
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiUnosEvidencijeActionPerformed

    private void jmiPretragaTaksistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaTaksistaActionPerformed
        FrmPretragaTaksista taksistafrm = new FrmPretragaTaksista(sluzbenik);
        JDialog dialog = new JDialog(this, "Prikaz taksista", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(taksistafrm, BorderLayout.CENTER);
        dialog.pack();
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiPretragaTaksistaActionPerformed

    private void jmiPretragaVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaVozilaActionPerformed
        FrmPretragaVozila vozilafrm = new FrmPretragaVozila(sluzbenik);
        JDialog dialog = new JDialog(this, "Prikaz vozila", true);
        dialog.setLayout(new BorderLayout());
        dialog.add(vozilafrm, BorderLayout.CENTER);
        dialog.pack();
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
        dialog.setVisible(true);
    }//GEN-LAST:event_jmiPretragaVozilaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.KRAJ);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
        } catch (Exception ex) {
            Logger.getLogger(FrmGlavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna(sluzbenik).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiPretragaTaksista;
    private javax.swing.JMenuItem jmiPretragaVozila;
    private javax.swing.JMenuItem jmiUnosEvidencije;
    private javax.swing.JMenuItem jmiUnosTaksista;
    private javax.swing.JMenuItem jmiUnosVozila;
    // End of variables declaration//GEN-END:variables
}
