/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Sluzbenik;
import domen.Taksista;
import forme.model.TaksistaTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;
import util.Util;

/**
 *
 * @author BOJAN
 */
public class FrmPretragaTaksista extends javax.swing.JPanel {
    
    private static Sluzbenik sluzbenik;

    /**
     * Creates new form FrmPretragaTaksista
     */
    public FrmPretragaTaksista(Sluzbenik s) {
        initComponents();
        this.sluzbenik = s;
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrikazTaksista = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        jLabel1.setText("Kriterijum pretrage:");

        btnPretrazi.setText("Pretra\u017Ei");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregled svih taksista"));

        jtblPrikazTaksista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPrikazTaksista);

        btnObrisi.setText("Obri\u0161i");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnObrisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalji)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnDetalji))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        if (jtxtPretraga.getText().trim().equals("")) {
            srediTabelu();
        } else {String taksista = null;
            if(jtxtPretraga.getText().contains(" ")){
                taksista = jtxtPretraga.getText().replace(" ", "_");
            }else{
            taksista = jtxtPretraga.getText().trim();
            }

            try {
                TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
                toZahtev.setOperacija(Konstante.NADJI_TAKSISTE);
                toZahtev.setParametar(taksista);
                Komunikacija.getInstance().posaljiZahtev(toZahtev);
                TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();

                List<Taksista> listaPronadjenihTaksista = (List<Taksista>) toOdgovor.getRezultat();

                if (listaPronadjenihTaksista.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da na\u0111e taksiste po zadatim vrednostima!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                }

                else {

                    TaksistaTableModel modelnadjeni = new TaksistaTableModel(listaPronadjenihTaksista);
                    jtblPrikazTaksista.setModel(modelnadjeni);
                    System.out.println("Sistem je na\u0161ao taksiste po zadatim vrednostima.");

                }

            } catch (Exception ex) {
                Logger.getLogger(FrmPretragaVozila.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int red = jtblPrikazTaksista.getSelectedRow();

        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati red!", "Gre\u0161ka",JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            TaksistaTableModel tpm = (TaksistaTableModel) jtblPrikazTaksista.getModel();
            List<Taksista> listaT = tpm.getListaTaksista();
            Taksista t = listaT.get(red);

            try {
                TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
                toZahtev.setOperacija(Konstante.OBRISI_TAKSISTU);
                toZahtev.setParametar(t);
                Komunikacija.getInstance().posaljiZahtev(toZahtev);
                TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();

                boolean obrisao = (boolean) toOdgovor.getRezultat();

                if (obrisao) {
                    tpm.obrisiRed(red);
                    JOptionPane.showMessageDialog(this, "Sistem je obrisao taksistu.");
                }
                else {
                    JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da obri\u0161e taksistu!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da obri\u0161e taksistu!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int odabrani = jtblPrikazTaksista.getSelectedRow();
        
        if (odabrani == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati taksistu!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
        } else {
            TaksistaTableModel ttm = (TaksistaTableModel) jtblPrikazTaksista.getModel();
            Taksista t = ttm.getTaksista(odabrani);
            Util.getInstance().put("izabrani_taksista", t);
            FrmDetaljiTaksista frdt = new FrmDetaljiTaksista(sluzbenik);
            JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
            dialog.dispose();
            frdt.setVisible(true);
            frdt.setDefaultCloseOperation(FrmUnosVozila.DISPOSE_ON_CLOSE);
            final Toolkit toolkit = Toolkit.getDefaultToolkit();
            final Dimension screenSize = toolkit.getScreenSize();
            final int x = (screenSize.width - frdt.getWidth()) / 2;
            final int y = (screenSize.height - frdt.getHeight()) / 2;
            frdt.setLocation(x, y);
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblPrikazTaksista;
    private javax.swing.JTextField jtxtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.VRATI_TAKSISTE);
            Komunikacija.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
            
            if (toOdgovor.getIzuzetak() != null) {
                throw (Exception) toOdgovor.getIzuzetak();
            }
            
            List<Taksista> listaTaksista = (List<Taksista>) toOdgovor.getRezultat();
            
            TaksistaTableModel ttm = new TaksistaTableModel(listaTaksista);
            jtblPrikazTaksista.setModel(ttm);
            
           
            
        } catch (Exception ex) {
            Logger.getLogger(FrmPretragaVozila.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
