/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Vozilo;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author BOJAN
 */
public class FrmUnosVozila extends javax.swing.JFrame {
    
    private final DateFormat df = new SimpleDateFormat("dd.MM.yyyy");

    /**
     * Creates new form FrmUnosVozaca
     */
    public FrmUnosVozila() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtVoziloID = new javax.swing.JTextField();
        jtxtDatumPocetkaSluzbe = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtVIN = new javax.swing.JTextField();
        jtxtRegistarskaOznaka = new javax.swing.JTextField();
        jtxtMarka = new javax.swing.JTextField();
        jtxtModel = new javax.swing.JTextField();
        jtxtUkupnaKilometraza = new javax.swing.JTextField();
        jbtnKreirajNovoVozilo = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID vozila:");

        jLabel2.setText("Datum po\u010Detka slu\u017Ebe:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o vozilu"));

        jLabel3.setText("VIN:");

        jLabel4.setText("Registarska oznaka:");

        jLabel5.setText("Marka");

        jLabel6.setText("Model:");

        jLabel7.setText("Ukupna kilometra\u017Ea:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(jtxtRegistarskaOznaka, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(84, 84, 84)
                        .addComponent(jtxtVIN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(jtxtUkupnaKilometraza, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)
                        .addComponent(jtxtMarka, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(73, 73, 73)
                        .addComponent(jtxtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtVIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtRegistarskaOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtUkupnaKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnKreirajNovoVozilo.setText("Kreiraj novo vozilo");
        jbtnKreirajNovoVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajNovoVoziloActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sa\u010Duvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSacuvaj)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtDatumPocetkaSluzbe, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jtxtVoziloID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnKreirajNovoVozilo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtVoziloID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatumPocetkaSluzbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnKreirajNovoVozilo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajNovoVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajNovoVoziloActionPerformed
    try{
        Date datumPocetkaSluzbe;
        
        if (jtxtDatumPocetkaSluzbe.getText().trim().equals("")) {
            datumPocetkaSluzbe = new Date();
        } else {
       
            try {
                df.parse(jtxtDatumPocetkaSluzbe.getText().trim());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Format datuma neispravan (dd.MM.yyyy)", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
            
            datumPocetkaSluzbe = df.parse(jtxtDatumPocetkaSluzbe.getText().trim());
        
            if (datumPocetkaSluzbe.after(new Date())) {
                JOptionPane.showMessageDialog(this, "Datum ne mo\u017Ee biti nakon dana\u0161njeg.", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Vozilo v = new Vozilo(-1, datumPocetkaSluzbe, " ", " ", " ", " ", 0);
       
        TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
        toZahtev.setOperacija(Konstante.KREIRAJ_VOZILO);
        toZahtev.setParametar(v);
        Komunikacija.getInstance().posaljiZahtev(toZahtev);
        TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
         
         int id = (int) toOdgovor.getRezultat();
         
         if (id==0) {
             JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da kreira vozilo.", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
         } else {
         
         jtxtVoziloID.setText(String.valueOf(id));
         jtxtDatumPocetkaSluzbe.setText(df.format(datumPocetkaSluzbe));
         
         
         jtxtDatumPocetkaSluzbe.setEditable(false);
        
        JOptionPane.showMessageDialog(this, "Sistem je kreirao novo vozilo.");
         }
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        
        }
    }//GEN-LAST:event_jbtnKreirajNovoVoziloActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
    try {
            
            if (jtxtVIN.getText().trim().equals("") || jtxtRegistarskaOznaka.getText().trim().equals("") || jtxtMarka.getText().trim().equals("") || jtxtModel.getText().trim().equals("") ||
               jtxtUkupnaKilometraza.getText().trim().equals("")){
                
                JOptionPane.showMessageDialog(this, "Polja moraju biti popunjena", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String ukKmVozila;
             try {
                 ukKmVozila = jtxtUkupnaKilometraza.getText().trim();
                if(ukKmVozila.contains(","))
                {
                ukKmVozila=ukKmVozila.replace(',', '.');
                }
                Double.parseDouble(ukKmVozila);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Morate uneti broj u polje Ukupna Kilometra\u017Ea!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
             
            if (jtxtUkupnaKilometraza.getText().trim().contains("-")) {
                JOptionPane.showMessageDialog(this, "Ne mo\u017Eete unositi negativne vrednosti!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
          
            if (jtxtVIN.getText().trim().length()!=17) {
                JOptionPane.showMessageDialog(this, "VIN mora sadr\u017Eati 17 znakova!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int id = Integer.parseInt(jtxtVoziloID.getText().trim());
           
            String vin = jtxtVIN.getText().trim();
            String registarskaOznaka = jtxtRegistarskaOznaka.getText().trim().toUpperCase();
            Date datumPS = df.parse(jtxtDatumPocetkaSluzbe.getText().trim());
            String marka = jtxtMarka.getText().trim();
            String model = jtxtModel.getText().trim();
            Double ukupnaKilometraza = Double.parseDouble(ukKmVozila);
            
            Vozilo v = new Vozilo(id, datumPS, vin,registarskaOznaka, marka, model, ukupnaKilometraza);
            
         TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
         toZahtev.setOperacija(Konstante.ZAPAMTI_VOZILO);
         toZahtev.setParametar(v);
         Komunikacija.getInstance().posaljiZahtev(toZahtev);
         TransferObjekatOdgovor toOdgovor = Komunikacija.getInstance().primiOdgovor();
        
         boolean sacuvano = (boolean) toOdgovor.getRezultat();
         
         if (sacuvano) {
             
             JOptionPane.showMessageDialog(this, "Sistem je zapamtio vozilo.");
             isprazniTxtPolja();
         } else {
             JOptionPane.showMessageDialog(this, "Sistem ne mo\u017Ee da zapamti vozilo!", "Gre\u0161ka", JOptionPane.ERROR_MESSAGE);
         }
            
            
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUnosVozila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUnosVozila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnKreirajNovoVozilo;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTextField jtxtDatumPocetkaSluzbe;
    private javax.swing.JTextField jtxtMarka;
    private javax.swing.JTextField jtxtModel;
    private javax.swing.JTextField jtxtRegistarskaOznaka;
    private javax.swing.JTextField jtxtUkupnaKilometraza;
    private javax.swing.JTextField jtxtVIN;
    private javax.swing.JTextField jtxtVoziloID;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        jtxtVoziloID.setEditable(false);
    }
    
        private void isprazniTxtPolja() {
        jtxtVoziloID.setText("");
        jtxtDatumPocetkaSluzbe.setText("");
        jtxtMarka.setText("");
        jtxtModel.setText("");
        jtxtRegistarskaOznaka.setText("");
        jtxtUkupnaKilometraza.setText("");
        jtxtVIN.setText("");
        jtxtDatumPocetkaSluzbe.setEditable(true);
    }
    
    

}
